// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkFfTA8T42VEsbiCK5u-f88BIBAlZZRkM',
    appId: '1:41824435314:web:5b70cd378f6b2c63aa16eb',
    messagingSenderId: '41824435314',
    projectId: 'notifications-app-d8c7e',
    authDomain: 'notifications-app-d8c7e.firebaseapp.com',
    storageBucket: 'notifications-app-d8c7e.firebasestorage.app',
    measurementId: 'G-CVENPRVH2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEnNA48YwWld-ZOR35ICR7BlmJ93gnxbQ',
    appId: '1:41824435314:android:40b484d91856b7c8aa16eb',
    messagingSenderId: '41824435314',
    projectId: 'notifications-app-d8c7e',
    storageBucket: 'notifications-app-d8c7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUrzqKmoIn4lM2LaD-DTkzs3hW3QEdYMA',
    appId: '1:41824435314:ios:aecf733732fdf5d1aa16eb',
    messagingSenderId: '41824435314',
    projectId: 'notifications-app-d8c7e',
    storageBucket: 'notifications-app-d8c7e.firebasestorage.app',
    iosBundleId: 'com.example.expenseSplitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUrzqKmoIn4lM2LaD-DTkzs3hW3QEdYMA',
    appId: '1:41824435314:ios:aecf733732fdf5d1aa16eb',
    messagingSenderId: '41824435314',
    projectId: 'notifications-app-d8c7e',
    storageBucket: 'notifications-app-d8c7e.firebasestorage.app',
    iosBundleId: 'com.example.expenseSplitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkFfTA8T42VEsbiCK5u-f88BIBAlZZRkM',
    appId: '1:41824435314:web:ad0e9df7b844358caa16eb',
    messagingSenderId: '41824435314',
    projectId: 'notifications-app-d8c7e',
    authDomain: 'notifications-app-d8c7e.firebaseapp.com',
    storageBucket: 'notifications-app-d8c7e.firebasestorage.app',
    measurementId: 'G-M4T20X26M1',
  );
}
